//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CS440DemoI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsInEnglish {
            get {
                return ((bool)(this["IsInEnglish"]));
            }
            set {
                this["IsInEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Neighborhood Informant")]
        public string TitleEnglish {
            get {
                return ((string)(this["TitleEnglish"]));
            }
            set {
                this["TitleEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Informante Barrio")]
        public string TitleSpanish {
            get {
                return ((string)(this["TitleSpanish"]));
            }
            set {
                this["TitleSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string SearchHKM {
            get {
                return ((string)(this["SearchHKM"]));
            }
            set {
                this["SearchHKM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("S")]
        public string SearchHK {
            get {
                return ((string)(this["SearchHK"]));
            }
            set {
                this["SearchHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settings")]
        public string SettingsLabelEnglish {
            get {
                return ((string)(this["SettingsLabelEnglish"]));
            }
            set {
                this["SettingsLabelEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ajustes")]
        public string SettingsLabelSpanish {
            get {
                return ((string)(this["SettingsLabelSpanish"]));
            }
            set {
                this["SettingsLabelSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English")]
        public string SettingsEngRadioEnglish {
            get {
                return ((string)(this["SettingsEngRadioEnglish"]));
            }
            set {
                this["SettingsEngRadioEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Inglés")]
        public string SettingsEngRadioSpanish {
            get {
                return ((string)(this["SettingsEngRadioSpanish"]));
            }
            set {
                this["SettingsEngRadioSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Spanish")]
        public string SettingSpaRadioEnglish {
            get {
                return ((string)(this["SettingSpaRadioEnglish"]));
            }
            set {
                this["SettingSpaRadioEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Español")]
        public string SettingSpaRadioSpanish {
            get {
                return ((string)(this["SettingSpaRadioSpanish"]));
            }
            set {
                this["SettingSpaRadioSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Language")]
        public string SettingsLangGBHEnglish {
            get {
                return ((string)(this["SettingsLangGBHEnglish"]));
            }
            set {
                this["SettingsLangGBHEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Idioma")]
        public string SettingsLangGBHSpanish {
            get {
                return ((string)(this["SettingsLangGBHSpanish"]));
            }
            set {
                this["SettingsLangGBHSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hot Keys")]
        public string SettingsHotKeyGBHEnglish {
            get {
                return ((string)(this["SettingsHotKeyGBHEnglish"]));
            }
            set {
                this["SettingsHotKeyGBHEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Teclas de acceso rápido")]
        public string SettingsHotKeyGBHSpanish {
            get {
                return ((string)(this["SettingsHotKeyGBHSpanish"]));
            }
            set {
                this["SettingsHotKeyGBHSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Apply Settings")]
        public string SettingsApplyBtnEnglish {
            get {
                return ((string)(this["SettingsApplyBtnEnglish"]));
            }
            set {
                this["SettingsApplyBtnEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aplicar configuración")]
        public string SettingsApplyBtnSpanish {
            get {
                return ((string)(this["SettingsApplyBtnSpanish"]));
            }
            set {
                this["SettingsApplyBtnSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Search")]
        public string HomeSearchBtnTTEnglish {
            get {
                return ((string)(this["HomeSearchBtnTTEnglish"]));
            }
            set {
                this["HomeSearchBtnTTEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Búsqueda")]
        public string HomeSearchBtnTTSpanish {
            get {
                return ((string)(this["HomeSearchBtnTTSpanish"]));
            }
            set {
                this["HomeSearchBtnTTSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Search")]
        public string SettingsHKESearchEnglish {
            get {
                return ((string)(this["SettingsHKESearchEnglish"]));
            }
            set {
                this["SettingsHKESearchEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Búsqueda")]
        public string SettingsHKESearchSpanish {
            get {
                return ((string)(this["SettingsHKESearchSpanish"]));
            }
            set {
                this["SettingsHKESearchSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Map")]
        public string HomeMapBtnTTEnglish {
            get {
                return ((string)(this["HomeMapBtnTTEnglish"]));
            }
            set {
                this["HomeMapBtnTTEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mapa")]
        public string HomeMapBtnTTSpanish {
            get {
                return ((string)(this["HomeMapBtnTTSpanish"]));
            }
            set {
                this["HomeMapBtnTTSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settings")]
        public string HomeSettBtnTTEnglish {
            get {
                return ((string)(this["HomeSettBtnTTEnglish"]));
            }
            set {
                this["HomeSettBtnTTEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ajustes")]
        public string HomeSettBtnTTSpanish {
            get {
                return ((string)(this["HomeSettBtnTTSpanish"]));
            }
            set {
                this["HomeSettBtnTTSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help")]
        public string HomeHelpBtnTTEnglish {
            get {
                return ((string)(this["HomeHelpBtnTTEnglish"]));
            }
            set {
                this["HomeHelpBtnTTEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ayudar")]
        public string HomeHelpBtnTTSpanish {
            get {
                return ((string)(this["HomeHelpBtnTTSpanish"]));
            }
            set {
                this["HomeHelpBtnTTSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string HomeHKM {
            get {
                return ((string)(this["HomeHKM"]));
            }
            set {
                this["HomeHKM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("H")]
        public string HomeHK {
            get {
                return ((string)(this["HomeHK"]));
            }
            set {
                this["HomeHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Home")]
        public string SettingsHKEHomeEnglish {
            get {
                return ((string)(this["SettingsHKEHomeEnglish"]));
            }
            set {
                this["SettingsHKEHomeEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Casa")]
        public string SettingsHKEHomeSpanish {
            get {
                return ((string)(this["SettingsHKEHomeSpanish"]));
            }
            set {
                this["SettingsHKEHomeSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string MapHKM {
            get {
                return ((string)(this["MapHKM"]));
            }
            set {
                this["MapHKM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M")]
        public string MapHK {
            get {
                return ((string)(this["MapHK"]));
            }
            set {
                this["MapHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Map")]
        public string SettingsHKEMapEnglish {
            get {
                return ((string)(this["SettingsHKEMapEnglish"]));
            }
            set {
                this["SettingsHKEMapEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mapa")]
        public string SettingsHKEMapSpanish {
            get {
                return ((string)(this["SettingsHKEMapSpanish"]));
            }
            set {
                this["SettingsHKEMapSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string HelpHKM {
            get {
                return ((string)(this["HelpHKM"]));
            }
            set {
                this["HelpHKM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("P")]
        public string HelpHK {
            get {
                return ((string)(this["HelpHK"]));
            }
            set {
                this["HelpHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help")]
        public string SettingsHKEHelpEnglish {
            get {
                return ((string)(this["SettingsHKEHelpEnglish"]));
            }
            set {
                this["SettingsHKEHelpEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ayudar")]
        public string SettingsHKEHelpSpanish {
            get {
                return ((string)(this["SettingsHKEHelpSpanish"]));
            }
            set {
                this["SettingsHKEHelpSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Settings")]
        public string SettingsHKESettingsEnglish {
            get {
                return ((string)(this["SettingsHKESettingsEnglish"]));
            }
            set {
                this["SettingsHKESettingsEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ajustes")]
        public string SettingsHKESettingsSpanish {
            get {
                return ((string)(this["SettingsHKESettingsSpanish"]));
            }
            set {
                this["SettingsHKESettingsSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("none")]
        public string SettingsHKM {
            get {
                return ((string)(this["SettingsHKM"]));
            }
            set {
                this["SettingsHKM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string SettingsHK {
            get {
                return ((string)(this["SettingsHK"]));
            }
            set {
                this["SettingsHK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Search By")]
        public string SearchByGBHEnglish {
            get {
                return ((string)(this["SearchByGBHEnglish"]));
            }
            set {
                this["SearchByGBHEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Búsqueda por")]
        public string SearchByGBHSpanish {
            get {
                return ((string)(this["SearchByGBHSpanish"]));
            }
            set {
                this["SearchByGBHSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Community")]
        public string SearchCommRadioEnglish {
            get {
                return ((string)(this["SearchCommRadioEnglish"]));
            }
            set {
                this["SearchCommRadioEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Comunidad")]
        public string SearchCommRadioSpanish {
            get {
                return ((string)(this["SearchCommRadioSpanish"]));
            }
            set {
                this["SearchCommRadioSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Block")]
        public string SearchBlockRadioEnglish {
            get {
                return ((string)(this["SearchBlockRadioEnglish"]));
            }
            set {
                this["SearchBlockRadioEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Bloque")]
        public string SearchBlockRadioSpanish {
            get {
                return ((string)(this["SearchBlockRadioSpanish"]));
            }
            set {
                this["SearchBlockRadioSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Current Search Options")]
        public string SearchCurrentGBHEnglish {
            get {
                return ((string)(this["SearchCurrentGBHEnglish"]));
            }
            set {
                this["SearchCurrentGBHEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Opciones Seach actuales")]
        public string SearchCurrentGBHSpanish {
            get {
                return ((string)(this["SearchCurrentGBHSpanish"]));
            }
            set {
                this["SearchCurrentGBHSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Save Current Search")]
        public string SearchSaveCurBtnEnglish {
            get {
                return ((string)(this["SearchSaveCurBtnEnglish"]));
            }
            set {
                this["SearchSaveCurBtnEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Guardar actual Searh")]
        public string SearchSaveCurBtnSpanish {
            get {
                return ((string)(this["SearchSaveCurBtnSpanish"]));
            }
            set {
                this["SearchSaveCurBtnSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Load Selected Saved Search")]
        public string SearchLoadCurBtnEnglish {
            get {
                return ((string)(this["SearchLoadCurBtnEnglish"]));
            }
            set {
                this["SearchLoadCurBtnEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Load Selected búsqueda guardada")]
        public string SearchLoadCurBtnSpanish {
            get {
                return ((string)(this["SearchLoadCurBtnSpanish"]));
            }
            set {
                this["SearchLoadCurBtnSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Export / Import Search Results")]
        public string SearchExportGBHEnglish {
            get {
                return ((string)(this["SearchExportGBHEnglish"]));
            }
            set {
                this["SearchExportGBHEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Exportación / Importación Resultados")]
        public string SearchExportGBHSpanish {
            get {
                return ((string)(this["SearchExportGBHSpanish"]));
            }
            set {
                this["SearchExportGBHSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Export Results")]
        public string SearchExportBtnEnglish {
            get {
                return ((string)(this["SearchExportBtnEnglish"]));
            }
            set {
                this["SearchExportBtnEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Exportar resultados")]
        public string SearchExportBtnSpanish {
            get {
                return ((string)(this["SearchExportBtnSpanish"]));
            }
            set {
                this["SearchExportBtnSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Search results:")]
        public string SearchResultsLabelEnglish {
            get {
                return ((string)(this["SearchResultsLabelEnglish"]));
            }
            set {
                this["SearchResultsLabelEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resultados de búsqueda:")]
        public string SearchResultsLabelSpanish {
            get {
                return ((string)(this["SearchResultsLabelSpanish"]));
            }
            set {
                this["SearchResultsLabelSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Help")]
        public string HelpHelpLabelEnglish {
            get {
                return ((string)(this["HelpHelpLabelEnglish"]));
            }
            set {
                this["HelpHelpLabelEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ayudar")]
        public string HelpHelpLabelSpanish {
            get {
                return ((string)(this["HelpHelpLabelSpanish"]));
            }
            set {
                this["HelpHelpLabelSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Import Results")]
        public string SearchImportBtnEnglish {
            get {
                return ((string)(this["SearchImportBtnEnglish"]));
            }
            set {
                this["SearchImportBtnEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Importar resultados")]
        public string SearchImportBtnSpanish {
            get {
                return ((string)(this["SearchImportBtnSpanish"]));
            }
            set {
                this["SearchImportBtnSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Neighborhood Map")]
        public string MapMapLabelEnglish {
            get {
                return ((string)(this["MapMapLabelEnglish"]));
            }
            set {
                this["MapMapLabelEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mapa barrio")]
        public string MapMapLabelSpanish {
            get {
                return ((string)(this["MapMapLabelSpanish"]));
            }
            set {
                this["MapMapLabelSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Refine Search By Statistics")]
        public string SearchRefineGBHEnglish {
            get {
                return ((string)(this["SearchRefineGBHEnglish"]));
            }
            set {
                this["SearchRefineGBHEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Filtrar búsqueda Por Estadísticas")]
        public string SearchRefineGBHSpanish {
            get {
                return ((string)(this["SearchRefineGBHSpanish"]));
            }
            set {
                this["SearchRefineGBHSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Advanced Options")]
        public string SearchExpanderHEnglish {
            get {
                return ((string)(this["SearchExpanderHEnglish"]));
            }
            set {
                this["SearchExpanderHEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Opciones avanzadas")]
        public string SearchExpanderHSpanish {
            get {
                return ((string)(this["SearchExpanderHSpanish"]));
            }
            set {
                this["SearchExpanderHSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Show top statistic results:")]
        public string SearchShowTopTBEnglish {
            get {
                return ((string)(this["SearchShowTopTBEnglish"]));
            }
            set {
                this["SearchShowTopTBEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Mostrar los resultados estadísticos:")]
        public string SearchShowTopTBSpanish {
            get {
                return ((string)(this["SearchShowTopTBSpanish"]));
            }
            set {
                this["SearchShowTopTBSpanish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string SearchShowTopValue {
            get {
                return ((string)(this["SearchShowTopValue"]));
            }
            set {
                this["SearchShowTopValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("By Statistic")]
        public string SearchByStatRadioEnglish {
            get {
                return ((string)(this["SearchByStatRadioEnglish"]));
            }
            set {
                this["SearchByStatRadioEnglish"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Por Estadística")]
        public string SearchByStatRadioSpanish {
            get {
                return ((string)(this["SearchByStatRadioSpanish"]));
            }
            set {
                this["SearchByStatRadioSpanish"] = value;
            }
        }
    }
}
